# Generated by Django 2.1.7 on 2019-06-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LNMonline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Merchant_Request_ID', models.CharField(blank=True, max_length=100, null=True)),
                ('Checkout_Request_ID', models.CharField(blank=True, max_length=50, null=True)),
                ('Result_Code', models.IntegerField(blank=True, null=True)),
                ('Result_Description', models.CharField(blank=True, max_length=120, null=True)),
                ('Amount', models.FloatField(blank=True, null=True)),
                ('Mpesa_Receipt_Number', models.CharField(blank=True, max_length=15, null=True)),
                ('Transaction_Date', models.DateTimeField(blank=True, null=True)),
                ('Phone_Number', models.CharField(blank=True, max_length=13, null=True)),
            ],
            options={
                'verbose_name_plural': 'Transactions',
            },
        ),
    ]
