# Generated by Django 2.1.7 on 2019-06-03 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlexHey', '0002_auto_20190603_1505'),
    ]

    operations = [
        migrations.DeleteModel(
            name='booking',
        ),
        migrations.RemoveField(
            model_name='car',
            name='car_make',
        ),
        migrations.RemoveField(
            model_name='car',
            name='car_model',
        ),
        migrations.DeleteModel(
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='model1',
            name='car_make',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='car',
        ),
        migrations.DeleteModel(
            name='make1',
        ),
        migrations.DeleteModel(
            name='model1',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
