# Generated by Django 2.1.7 on 2019-05-22 11:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PlexHey', '0002_remove_booking_identificationumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='make1',
            name='make_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
