# Generated by Django 2.1.7 on 2019-05-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlexHey', '0003_make1_make_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='profile/'),
        ),
    ]
