# Generated by Django 2.1.7 on 2019-06-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlexHey', '0004_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='phonenumber',
            field=models.CharField(default=True, max_length=13, null=True),
        ),
    ]
