# Generated by Django 2.1.7 on 2019-06-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlexHey', '0006_auto_20190603_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='phonenumber',
            field=models.CharField(default=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Phone_Number',
            field=models.CharField(default=True, max_length=15, null=True),
        ),
    ]
