# Generated by Django 2.1.7 on 2019-06-09 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlexHey', '0006_auto_20190604_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='pickupdate',
        ),
    ]
