# Generated by Django 2.1.7 on 2019-06-09 19:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PlexHey', '0007_remove_booking_pickupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='pickupdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
