# Generated by Django 2.1.7 on 2019-06-12 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlexHey', '0009_auto_20190611_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='pickupdate',
        ),
    ]
