# Generated by Django 2.1.7 on 2019-06-12 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlexHey', '0010_remove_booking_pickupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='pickupdate',
            field=models.DateField(null=True),
        ),
    ]
