# Generated by Django 2.1.7 on 2019-06-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlexHey', '0011_booking_pickupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='amount',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
