# Generated by Django 2.1.7 on 2019-06-13 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlexHey', '0013_booking_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Driving',
        ),
    ]
