# Generated by Django 2.1.7 on 2019-06-13 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlexHey', '0014_remove_profile_driving'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Driving_license',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='profile/'),
        ),
    ]
